version: "2"

run:
  go: "1.24"
  tests: true

linters:
  enable:
    - arangolint
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    # - contextcheck
    - copyloopvar
    # - cyclop
    - decorder
    # - depguard
    # - dogsled
    # - dupl
    - dupword
    - durationcheck
    - embeddedstructfieldcheck
    # - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    # - exhaustruct
    - exptostd
    # - fatcontext
    # - forbidigo
    - forcetypeassert
    # - funcorder
    # - funlen
    - ginkgolinter
    - gocheckcompilerdirectives
    # - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    # - gocognit - Computes and checks the cognitive complexity of functions.
    # - goconst - Finds repeated strings that could be replaced by a constant.
    - gocritic
    # - gocyclo
    # - godoclint
    # - godot
    # - godox
    - goheader
    # - gomoddirectives
    - gomodguard
    - goprintffuncname
    # - gosec
    - gosmopolitan
    - govet
    - grouper
    - iface
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    - intrange
    - iotamixing
    # - ireturn
    # - lll
    - loggercheck
    - maintidx
    # - makezero
    # - mirror
    # - misspell
    # - mnd
    # - modernize
    # - musttag
    # - nakedret
    # - nestif
    - nilerr
    - nilnesserr
    - nilnil
    # - nlreturn
    # - noctx
    # - noinlineerr
    - nolintlint
    # - nonamedreturns
    - nosprintfhostport
    - paralleltest
    # - perfsprint
    # - prealloc
    - predeclared
    # - promlinter
    - protogetter
    - reassign
    - recvcheck
    # - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    # - tagliatelle
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    # - unparam
    - unqueryvet
    - unused
    - usestdlibvars
    - usetesting
    # - varnamelen
    - wastedassign
    - whitespace
    # - wrapcheck
    - wsl_v5
    - zerologlint

  # All available settings of specific linters.
  settings:
    staticcheck:
      checks:
        - all

        # Disable: Incorrect or missing package comment
        # See: https://staticcheck.dev/docs/checks/#ST1000
        - "-ST1000"

  # Defines a set of rules to ignore issues.
  # It does not skip the analysis, and so does not ignore "typecheck" errors.
  exclusions:
    generated: lax
    rules:
      - path: _test\.go
        linters:
          - gocyclo

    paths:
      - "./frontend/"
      - vendor

formatters:
  enable:
    - gci
    - gofmt
    # - golines

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
