version: "2"

run:
  go: "1.24"
  tests: true

linters:
  enable:
    - arangolint
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    # - contextcheck
    - copyloopvar
    # - cyclop
    - decorder
    # - depguard
    # - dogsled
    # - dupl
    - dupword
    - durationcheck
    - embeddedstructfieldcheck
    # - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    # - exhaustruct
    - exptostd
    # - fatcontext
    # - forbidigo
    - forcetypeassert
    # - funcorder
    # - funlen
    - ginkgolinter
    - gocheckcompilerdirectives
    # - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    # - gocognit - Computes and checks the cognitive complexity of functions.
    # - goconst - Finds repeated strings that could be replaced by a constant.
    - gocritic
    # - gocyclo - Computes and checks the cyclomatic complexity of functions.
    # - godoclint -  Checks Golang's documentation practice.
    # - godot - Checks that comments end in a period.
    # - godox - Detects usage of FIXME, TODO and other keywords inside comments.
    - goheader
    # - gomoddirectives - Manage the use of 'replace', 'retract', and 'excludes' directives in go.mod.
    - gomodguard
    - goprintffuncname
    # - gosec - Inspects source code for security problems.
    - gosmopolitan
    - govet
    - grouper
    - iface
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    - intrange
    - iotamixing
    # - ireturn - Accept Interfaces, Return Concrete Types.
    # - lll - Reports long lines.
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    # - mnd - An analyzer to detect magic numbers.
    - modernize
    - musttag
    # - nakedret - Checks that functions with naked returns are not longer than a maximum size (can be zero).
    # - nestif - Reports deeply nested if statements.
    - nilerr
    - nilnesserr
    - nilnil
    - nlreturn
    # - noctx - Detects function and method with missing usage of context.Context.
    # - noinlineerr - Disallows inline error handling (`if err := ...; err != nil {`).
    - nolintlint
    # - nonamedreturns - Reports all named returns.
    - nosprintfhostport
    - paralleltest
    - perfsprint
    # - prealloc
    - predeclared
    # - promlinter
    - protogetter
    - reassign
    - recvcheck
    # - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    # - tagliatelle
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    # - unparam
    - unqueryvet
    - unused
    - usestdlibvars
    - usetesting
    # - varnamelen
    - wastedassign
    - whitespace
    # - wrapcheck
    - wsl_v5
    - zerologlint

  # All available settings of specific linters.
  settings:
    staticcheck:
      checks:
        - all

        # Disable: Incorrect or missing package comment
        # See: https://staticcheck.dev/docs/checks/#ST1000
        - "-ST1000"

    modernize:
      disable:
        # Replace interface{} with any.
        # With gorm UpdateColumns(map[string]interface{}{"field": value}) this
        # does not work as gorm expects interface{} specifically.
        - any

  # Defines a set of rules to ignore issues.
  # It does not skip the analysis, and so does not ignore "typecheck" errors.
  exclusions:
    generated: lax
    rules:
      - path: _test\.go
        linters:
          - gocyclo

    paths:
      - "./frontend/"
      - vendor

formatters:
  enable:
    - gci
    - gofmt
    # - golines

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
