# Example of a configuration

[server]
# To interact with the server API
endpoint = "http://10.0.0.1:8080"
secret = "supersegreto"

[database]
user = "sasso"
password = "password"
database = "sasso-vpn"
host = "localhost"
port = 5432

[wireguard]
# The server's WireGuard public key
public_key = "qjYzM9d9hoaw1L5sDk7DjjdNcfX0UVrkoF7Vuztzajw="
# The server's public endpoint for clients to connect to
endpoint = "130.136.201.124:51820"
# The subnet used for the WireGuard VPN
vpn_subnet = "10.253.0.0/24"

# The subnet used for the VMs. This must match the subnet configured in the
# router
vms_subnet = "10.254.0.0/16"

# Name of the interface used for the WireGuard VPN
interface_name = "sasso"

[firewall]
type = "shorewall"

[firewall.shorewall]
# Zones used in the firewall configuration
vpn = "vpn"
sasso = "vms"
# Base path of the shorewall configuration. Usually /etc/shorewall
base_path = "/etc/shorewall"
# To avoid conflicts with existing shorewall configuration, we use an identifier
# that is generated with an uuid. Use the `uuidgen` command to generate a new
# one if you want to use this configuration on your machine. Please note that
# changing this value will cause the service to lose track of existing rules and
# will cause issues. If this value is changed, make sure to clean up existing
# rules in shorewall configuration by hand.
id = "4110bfa0-16aa-4109-b864-da67ac4c4755"
